### ISSUE TITLE
2way communication

### ISSUE THREAD

**Issue by OliverMichalakKreait** [nickromano/WatchSync#1]
Hei, this is an indispensable helper sitting on top of Swifts types and codables - kreait idea.

More often than not, I find myself in the situation of two way communications where the watch and phone have to request-and-response to each other.

watch: sendMessage A requesting some data
phone: subscribed to A, sendMessage B with some payload data
watch: subscribed to B, processing it

This leads to very loosely coupled logic but maybe, this could be solved in WatchSync as well by means of:

watch: sendRequest A and gives a responseCallback expecting B
phone: responds to Request A and prepares B as a returned object
watch: responseCallback is called with B

Can you elaborate how close WatchSync is to that approach or do you see any serious blockers?
#thx

**Comment by nickromano** [comment]
Hey Oliver, I like how Apple has offered the responseCallback's as an option for real-time messaging, but in practice, I've seen the devices lose reachability very frequently which is why I don't like to completely rely on that form of messaging.

WatchSync uses real-time messaging when it's available and transferUserInfo when reachability is false so that messages are guaranteed to be delivered. Since transferUserInfo doesn't have a response callback I would recommend going with the first option you mentioned above.

Thanks!
Nick
